"""Emission layer: generates Markdown files from a BlogModel.

EMISSION LAYER — no business logic allowed here.
Reads from :class:`~zensical_blog.models.BlogModel` only.
Writes to ``docs/.bloggen/`` (generated root) and appends sentinel blocks
to canonical user-facing files.
"""

from __future__ import annotations

import logging
from pathlib import Path

from zensical_blog.models import (
    ArchivePeriod,
    BlogModel,
    BuildWarning,
    Post,
    TaxonomyTerm,
)

log = logging.getLogger(__name__)

_SENTINEL_START = "<!-- zensical-blog:generated:start -->"
_SENTINEL_COMMENT = (
    "<!-- regenerated by zensical-blog; do not edit between these markers -->"
)
_SENTINEL_END = "<!-- zensical-blog:generated:end -->"


# ---------------------------------------------------------------------------
# Sentinel protocol
# ---------------------------------------------------------------------------


def _wrap_sentinel(content: str) -> str:
    """Wrap *content* in sentinel markers."""
    return f"{_SENTINEL_START}\n{_SENTINEL_COMMENT}\n{content}\n{_SENTINEL_END}"


def apply_sentinel(file_path: Path, generated_block: str) -> None:
    """Write *generated_block* into *file_path* using the sentinel protocol.

    - If the file doesn't exist: create it with only the sentinel block.
    - If the file exists without markers: append a blank line + sentinel block.
    - If the file exists with markers: replace content between the markers.
    - Writes only if the resulting content differs from the current file.
    """
    file_path.parent.mkdir(parents=True, exist_ok=True)
    wrapped = _wrap_sentinel(generated_block)

    if not file_path.exists():
        file_path.write_text(wrapped + "\n", encoding="utf-8")
        return

    existing = file_path.read_text(encoding="utf-8")

    if _SENTINEL_START in existing and _SENTINEL_END in existing:
        before = existing[: existing.index(_SENTINEL_START)]
        after = existing[existing.index(_SENTINEL_END) + len(_SENTINEL_END) :]
        new_content = before + wrapped + after
    else:
        # Append after existing content
        separator = "\n\n" if existing.rstrip() else ""
        new_content = existing.rstrip() + separator + wrapped + "\n"

    if new_content == existing:
        return  # No change — skip write

    file_path.write_text(new_content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Markdown generation helpers
# ---------------------------------------------------------------------------


def _post_listing(posts: tuple, blog_dir: str) -> str:
    """Return a Markdown post listing for *posts*."""
    if not posts:
        return "_No posts yet._\n"

    lines: list[str] = []
    for post in posts:
        lines.append(f"### [{post.title}]({post.url_path})")
        lines.append("")

        meta_parts = [f"*{post.date.isoformat()}*"]

        if post.tags:
            tag_links = " · ".join(
                f"[{t}](/{blog_dir}/tag/{_slug_for_tag(t, post)}/) "
                for t in post.tags
            )
            meta_parts.append(f"Tags: {tag_links.strip()}")

        if post.categories:
            cat_links = " · ".join(
                f"[{c}](/{blog_dir}/category/{_slug_for_tag(c, post)}/)"
                for c in post.categories
            )
            meta_parts.append(f"Categories: {cat_links.strip()}")

        lines.append(" &nbsp;|&nbsp; ".join(meta_parts))
        lines.append("")

        if post.excerpt:
            lines.append(post.excerpt)
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _slug_for_tag(label: str, post: Post) -> str:  # type: ignore[name-defined]
    """Best-effort slug for a taxonomy label when full registry isn't available."""
    from zensical_blog.slugifier import slugify as _slugify

    return _slugify(label)


# ---------------------------------------------------------------------------
# Blog index (US1)
# ---------------------------------------------------------------------------


def emit_blog_index(model: BlogModel) -> None:
    """Generate the blog index listing and apply it to the canonical index file."""
    config = model.config
    blog_dir = config.blog_dir

    listing = f"## Recent Posts\n\n{_post_listing(model.posts, blog_dir)}"

    # Write generated artifact
    generated_path = config.generated_root / blog_dir / "lists" / "latest.md"
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    # Apply to canonical file
    canonical = config.docs_dir / blog_dir / "index.md"
    apply_sentinel(canonical, listing)


# ---------------------------------------------------------------------------
# Archive pages (US2)
# ---------------------------------------------------------------------------


def emit_archive_landing(model: BlogModel) -> None:
    """Generate the archive landing page."""
    config = model.config
    blog_dir = config.blog_dir

    if not model.archives:
        return

    lines = ["## Archives", ""]
    lines.append("| Year | Posts |")
    lines.append("|------|-------|")
    for period in model.archives:
        lines.append(
            f"| [{period.year}](/{blog_dir}/archive/{period.year}/) "
            f"| {len(period.posts)} |"
        )
    lines.append("")
    listing = "\n".join(lines)

    generated_path = (
        config.generated_root / blog_dir / "archive" / "index.generated.md"
    )
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    canonical = config.docs_dir / blog_dir / "archive" / "index.md"
    apply_sentinel(canonical, listing)


def emit_archive_year(model: BlogModel, period: ArchivePeriod) -> None:
    """Generate the per-year archive page."""
    config = model.config
    blog_dir = config.blog_dir

    listing = f"## Posts from {period.year}\n\n{_post_listing(period.posts, blog_dir)}"

    generated_path = (
        config.generated_root / blog_dir / "archive" / f"{period.year}.generated.md"
    )
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    canonical = config.docs_dir / blog_dir / "archive" / f"{period.year}.md"
    apply_sentinel(canonical, listing)


# ---------------------------------------------------------------------------
# Tag pages (US3)
# ---------------------------------------------------------------------------


def emit_tags_landing(model: BlogModel) -> None:
    """Generate the tags landing page."""
    config = model.config
    blog_dir = config.blog_dir

    if not model.tags:
        return

    lines = ["## Tags", ""]
    lines.append("| Tag | Posts |")
    lines.append("|-----|-------|")
    for term in model.tags:
        lines.append(
            f"| [{term.label}](/{blog_dir}/tag/{term.slug}/) | {len(term.posts)} |"
        )
    lines.append("")
    listing = "\n".join(lines)

    generated_path = (
        config.generated_root / blog_dir / "tag" / "index.generated.md"
    )
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    canonical = config.docs_dir / blog_dir / "tag" / "index.md"
    apply_sentinel(canonical, listing)


def emit_tag_page(model: BlogModel, term: TaxonomyTerm) -> None:
    """Generate a per-tag page."""
    config = model.config
    blog_dir = config.blog_dir

    listing = (
        f'## Posts tagged \u201c{term.label}\u201d\n\n'
        f'{_post_listing(term.posts, blog_dir)}'
    )

    generated_path = (
        config.generated_root / blog_dir / "tag" / f"{term.slug}.generated.md"
    )
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    canonical = config.docs_dir / blog_dir / "tag" / f"{term.slug}.md"
    apply_sentinel(canonical, listing)


# ---------------------------------------------------------------------------
# Category pages (US3)
# ---------------------------------------------------------------------------


def emit_categories_landing(model: BlogModel) -> None:
    """Generate the categories landing page."""
    config = model.config
    blog_dir = config.blog_dir

    if not model.categories:
        return

    lines = ["## Categories", ""]
    lines.append("| Category | Posts |")
    lines.append("|----------|-------|")
    for term in model.categories:
        lines.append(
            f"| [{term.label}](/{blog_dir}/category/{term.slug}/) | {len(term.posts)} |"
        )
    lines.append("")
    listing = "\n".join(lines)

    generated_path = (
        config.generated_root / blog_dir / "category" / "index.generated.md"
    )
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    canonical = config.docs_dir / blog_dir / "category" / "index.md"
    apply_sentinel(canonical, listing)


def emit_category_page(model: BlogModel, term: TaxonomyTerm) -> None:
    """Generate a per-category page."""
    config = model.config
    blog_dir = config.blog_dir

    listing = (
        f'## Posts in \u201c{term.label}\u201d\n\n'
        f'{_post_listing(term.posts, blog_dir)}'
    )

    generated_path = (
        config.generated_root / blog_dir / "category" / f"{term.slug}.generated.md"
    )
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    generated_path.write_text(listing, encoding="utf-8")

    canonical = config.docs_dir / blog_dir / "category" / f"{term.slug}.md"
    apply_sentinel(canonical, listing)


# ---------------------------------------------------------------------------
# Nav assurance (US5)
# ---------------------------------------------------------------------------


def _check_nav(model: BlogModel) -> BuildWarning | None:
    """Return a warning if the Blog nav entry is absent from ``mkdocs.yml``."""
    config = model.config
    mkdocs_yml = config.docs_dir.parent / "mkdocs.yml"
    if not mkdocs_yml.is_file():
        return None  # No mkdocs.yml — no nav to check

    from ruamel.yaml import YAML

    yaml = YAML()
    with open(mkdocs_yml, encoding="utf-8") as fh:
        data = yaml.load(fh) or {}

    nav = data.get("nav") or []
    for entry in nav:
        if isinstance(entry, dict):
            for label, path in entry.items():
                if label == config.nav_label and path == config.nav_path:
                    return None

    return BuildWarning(
        code="MISSING_NAV_ENTRY",
        message=(
            f"Blog nav entry not found in mkdocs.yml. "
            f"Add `- {config.nav_label}: {config.nav_path}` to your nav, "
            f"or run `zensical-blog build --apply-nav` to patch it automatically."
        ),
    )


# ---------------------------------------------------------------------------
# Top-level orchestrator
# ---------------------------------------------------------------------------


def emit_all(model: BlogModel) -> None:
    """Emit all blog pages for *model*.

    Orchestration order:
    1. Blog index
    2. Archive landing + per-year pages
    3. Tags landing + per-tag pages
    4. Categories landing + per-category pages
    5. Nav assurance check (warning only, no writes)
    """
    config = model.config

    # Ensure generated root exists
    config.generated_root.mkdir(parents=True, exist_ok=True)

    emit_blog_index(model)

    if config.enable_archive_landing:
        emit_archive_landing(model)
        for period in model.archives:
            emit_archive_year(model, period)

    if config.enable_tags:
        emit_tags_landing(model)
        for term in model.tags:
            emit_tag_page(model, term)

    if config.enable_categories:
        emit_categories_landing(model)
        for term in model.categories:
            emit_category_page(model, term)

    nav_warning = _check_nav(model)
    if nav_warning:
        log.warning(nav_warning.message)
